In [ ]:
import numpy as np
import sys
from pathlib import Path
sys.path.insert(0, str(Path.cwd().parent)) 
from commom_utils.systems import *
from commom_utils.ode_system import ODESystem, check_system_ok, SyntheticDataGenerator
from commom_utils.system_config import create_system, SYSTEM_CONFIGS
from gauss_newton.utils import plot_solution
import numpy as np
import matplotlib.pyplot as plt
from gauss_newton.problem import MultipleShooting
from gauss_newton.collocation_shooting import CollocationShooting
from gauss_newton.normal_equations import (MultipleShootingAccum,
                                           CollocationShootingAccum)
from gauss_newton.adaptive import run_optimization_adaptive


In [2]:
model_name = "Attractor"
system, c0, theta_true, delta_theta = create_system(SYSTEM_CONFIGS[model_name])
theta_init = theta_true + delta_theta if delta_theta is not None else theta_true

In [3]:
t0 = 0
t1 = 10
generator_main = SyntheticDataGenerator(system, sigma=3e-8, perturb_initial=True, perturbation_scale=0.0, use_jax=1)

t_batches, measured_batches, state_batches, inp_signals = generator_main.generate(
    c0=c0,
    theta=theta_true,
    time_intervals=[(t0, t1)],
    n_measurements=50
)

generator_debug = SyntheticDataGenerator(system, sigma=0.0, perturb_initial=True, perturbation_scale=0.0, use_jax=1)

t_batches_debug, measured_batches_debug, state_batches_debug, inp_signals_batches_debug = generator_debug.generate(
    c0=c0,
    theta=theta_true,
    time_intervals=[(t0, t1)],
    n_measurements=1000
)

In [4]:
theta_true, theta_init

(array([10.        , 28.        ,  2.66666667]),
 array([ 9.91391694, 32.20393757,  4.64171709]))

In [5]:
system.n_obs

3

In [6]:
# Для каждого батча (эксперимента) создаём отдельную фигуру или субплот
for batch_idx, (t_batch, t_batch_debug, meas_batch, fill_batch, fill_batch_debug, inp_signals_debug) in enumerate(
        zip(t_batches, t_batches_debug, measured_batches, state_batches, state_batches_debug, inp_signals_batches_debug)):

    plt.figure(figsize=(12, 6))
    
    # 1. Измерения (зелёные крестики) – для каждой переменной отдельный цвет и легенда
    n_meas = meas_batch.shape[1]  # количество измеряемых переменных
    n_inp_signal = system.nu
    for i in range(n_meas):
        plt.scatter(t_batch, meas_batch[:, i], marker='x', label=f'Measurement var {i}', alpha=0.7)


    # 2. Оценочные траектории (сплошные линии) – для каждого состояния
    n_states = fill_batch_debug.shape[1]
    for i in range(n_states):
        plt.plot(t_batch_debug, fill_batch_debug[:, i], '-', label=f'Real state {i}', linewidth=2)

    # for i in range(n_inp_signal):
    #     plt.plot(t_batch_debug, inp_signals_debug[:, i], '-',  label=f'Input signal {i}', linewidth=2)
    
    # 3. Настройки подписей
    plt.xlabel('Time (s)', fontsize=12)
    plt.ylabel('Values', fontsize=12)
    plt.title(f'Batch {batch_idx+1}: Measurements vs Estimated trajectories', fontsize=14)
    plt.grid(True, alpha=0.3)
    plt.legend(loc='best', fontsize=10)
    
    plt.tight_layout()
    plt.show()

<Figure size 1200x600 with 1 Axes>

In [7]:
theta_init, theta_true

(array([ 9.91391694, 32.20393757,  4.64171709]),
 array([10.        , 28.        ,  2.66666667]))

In [ ]:
# optimization_config.py (исправленная версия с доверительными интервалами)
import numpy as np
import matplotlib.pyplot as plt

class OptimizationConfig:
    """Конфигурация оптимизации для multiple shooting."""
    def __init__(self, n_obs):
        self.gamma = np.ones(n_obs)      # веса измерений
        self.n_iter = 30                   # верхняя граница итераций
        self.c0_cost = 1.0                  # вес начальной точки в интервале
        self.n_shoot = 50
        # Элементов коллокации на интервал сетки (Colloc*-классы). Сетка здесь
        # грубая (dt~0.2), а Лоренц быстрый: n_sub=2 даёт ошибку θ ~1e-2 из-за
        # дискретизации, n_sub=4 — ~5e-4 при той же скорости
        self.n_sub = 4

def setup_problem(system, problem_class, config, state_measured_batches,
                  t_eval_batches, t_eval_debug, state_full_debug, theta_true):
    kwargs = {}
    if issubclass(problem_class, CollocationShooting):
        # свои параметры интегратора: n_sub, K, newton_tol, rootfinder_options...
        kwargs['n_sub'] = config.n_sub
    else:
        # без use_jax=True шуты интегрируются scipy-циклом — в разы медленнее
        kwargs['use_jax'] = True
    problem = problem_class(system, N_shoot=config.n_shoot, gamma=config.gamma,
                            c0_cost=config.c0_cost, **kwargs)
    for state_meas, t_meas in zip(state_measured_batches, t_eval_batches):
        problem.add_batch(state_meas, t_meas)
    problem.full_trajectory = (t_eval_debug, state_full_debug)
    problem.theta_true = theta_true
    return problem

# ====================================================================
# Основной блок
# ====================================================================
if __name__ == "__main__":

    # Четыре взаимозаменяемых класса задачи:
    #   MultipleShooting         — вариационные уравнения, JAX (явный интегратор)
    #   CollocationShooting      — коллокации Радо IIA (жёсткие системы)
    #   MultipleShootingAccum    — то же + H и g копятся, большая J не строится
    #   CollocationShootingAccum — коллокации + накопление H и g
    problem_class = CollocationShootingAccum

    config = OptimizationConfig(system.n_obs)
    problem = setup_problem(system, problem_class, config,
                            measured_batches, t_batches,
                            t_batches_debug, state_batches_debug, theta_true)
    theta0 = theta_init   # theta определена ранее

    theta_full = problem.make_full_theta(theta0, n_iter = 10)
    # mu и lambda подбираются автоматически, ручной config больше не нужен
    theta_full, hist = run_optimization_adaptive(problem, theta_full,
                                                 n_iter=config.n_iter)
    theta_hist = hist['theta']
    r_meas_hist, r_cont_hist = hist['r_meas'], hist['r_cont']
    ci_low_hist, ci_high_hist = hist['ci_low'], hist['ci_high']


In [ ]:

plot_solution(
    problem = problem, 
    theta_hist = theta_hist,
    plot_xy=1,
    plot_theta=True,
    plot_trajectory=1,
    plot_true_solution=False,
    plot_residuals=True,
    plot_measurements = 1,
    r_meas_hist=r_meas_hist,
    r_cont_hist=r_cont_hist,
    index=-1,
    theta_true=None,
    # ci_low_hist=ci_low_hist,    # <-- добавить
    # ci_high_hist=ci_high_hist,  # <-- добавить
    #state_names=['a_y', 'w_z'],
    #param_names=['C<sub>f</sub>', 'C<sub>r</sub>', 'a<sub>rel</sub>', 'I<sub>norm</sub>']
   # param_names=[f'θ_{i}' for i in range( system.n_theta)]
)

In [ ]:
fig = plt.figure(figsize=(30, 25))
plot_solution(
    None, problem, theta_hist,
    plot_xy=1,
    plot_theta=True,
    plot_trajectory=1,
    plot_true_solution=True,
    plot_residuals=True,
    plot_measurements = 1,
    r_meas_hist=r_meas_hist,
    r_cont_hist=r_cont_hist,
    index=0,
    theta_true=theta_true,
    ci_low_hist=ci_low_hist,    # <-- добавить
    ci_high_hist=ci_high_hist,  # <-- добавить
    param_names=[f'θ_{i}' for i in range( system.n_theta)]
)

In [41]:
theta_true, theta_hist[-1][:len(theta_true)]

(array([ 0.05      , -0.08726646]), array([ 0.05145798, -0.10184656]))

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.animation as animation

fig = plt.figure(figsize=(30, 25))

def animate_gauss(frame):
    fig.clear()
    plt.clf()
    plot_solution(
    fig, 
    problem, 
    theta_hist, 
    plot_xy=0,               # покажет x(t) и y(t)
    plot_theta=1,            # покажет сходимость параметров
    plot_trajectory=1,       # фазовая траектория (3D для систем с nx >= 3)
    plot_true_solution=True,    # если есть истинная траектория
    plot_residuals=0,        # добавить график невязок
    r_meas_hist=r_meas_hist,    # ваша история невязок измерений
    r_cont_hist=r_cont_hist,     # ваша история невязок непрерывности
    index=frame,                   # последняя итерация
    theta_true=theta_true       # истинные параметры (опционально)
)
anim = animation.FuncAnimation(
    fig, animate_gauss, frames=10, interval=500, repeat=True
)

plt.show()

In [22]:
anim.save("gauss_newton/demo.gif", writer="pillow")

batch 0
batch 0
batch 0
batch 0
batch 0
batch 0
batch 0
batch 0
batch 0
batch 0
batch 0


<Figure size 640x480 with 0 Axes>