In [1]:

import numpy as np
import sys
from pathlib import Path
sys.path.insert(0, str(Path.cwd().parent)) 
from commom_utils.systems import *
from commom_utils.ode_system import ODESystem, check_system_ok, SyntheticDataGenerator
from commom_utils.system_config import create_system, SYSTEM_CONFIGS
from gauss_newton.utils import plot_solution
import numpy as np
import matplotlib.pyplot as plt
from gauss_newton.gauss_newton_math import MultipleShooting, run_optimization


In [2]:
model_name = "Attractor"
system, c0, theta_true, delta_theta = create_system(SYSTEM_CONFIGS[model_name])
theta_init = theta_true + delta_theta if delta_theta is not None else theta_true

In [3]:
t0 = 0
t1 = 10
generator_main = SyntheticDataGenerator(system, sigma=3e-8, perturb_initial=True, perturbation_scale=0.0, use_jax=1)

t_batches, measured_batches, state_batches, inp_signals = generator_main.generate(
    c0=c0,
    theta=theta_true,
    time_intervals=[(t0, t1)],
    n_measurements=50
)

generator_debug = SyntheticDataGenerator(system, sigma=0.0, perturb_initial=True, perturbation_scale=0.0, use_jax=1)

t_batches_debug, measured_batches_debug, state_batches_debug, inp_signals_batches_debug = generator_debug.generate(
    c0=c0,
    theta=theta_true,
    time_intervals=[(t0, t1)],
    n_measurements=1000
)

In [4]:
theta_true, theta_init

(array([10.        , 28.        ,  2.66666667]),
 array([ 9.91391694, 32.20393757,  4.64171709]))

In [5]:
system.n_obs

3

In [6]:
# Для каждого батча (эксперимента) создаём отдельную фигуру или субплот
for batch_idx, (t_batch, t_batch_debug, meas_batch, fill_batch, fill_batch_debug, inp_signals_debug) in enumerate(
        zip(t_batches, t_batches_debug, measured_batches, state_batches, state_batches_debug, inp_signals_batches_debug)):

    plt.figure(figsize=(12, 6))
    
    # 1. Измерения (зелёные крестики) – для каждой переменной отдельный цвет и легенда
    n_meas = meas_batch.shape[1]  # количество измеряемых переменных
    n_inp_signal = system.nu
    for i in range(n_meas):
        plt.scatter(t_batch, meas_batch[:, i], marker='x', label=f'Measurement var {i}', alpha=0.7)


    # 2. Оценочные траектории (сплошные линии) – для каждого состояния
    n_states = fill_batch_debug.shape[1]
    for i in range(n_states):
        plt.plot(t_batch_debug, fill_batch_debug[:, i], '-', label=f'Real state {i}', linewidth=2)

    # for i in range(n_inp_signal):
    #     plt.plot(t_batch_debug, inp_signals_debug[:, i], '-',  label=f'Input signal {i}', linewidth=2)
    
    # 3. Настройки подписей
    plt.xlabel('Time (s)', fontsize=12)
    plt.ylabel('Values', fontsize=12)
    plt.title(f'Batch {batch_idx+1}: Measurements vs Estimated trajectories', fontsize=14)
    plt.grid(True, alpha=0.3)
    plt.legend(loc='best', fontsize=10)
    
    plt.tight_layout()
    plt.show()

<Figure size 1200x600 with 1 Axes>

In [7]:
theta_init, theta_true

(array([ 9.91391694, 32.20393757,  4.64171709]),
 array([10.        , 28.        ,  2.66666667]))

In [10]:
# optimization_config.py (исправленная версия с доверительными интервалами)
import numpy as np
import matplotlib.pyplot as plt

class OptimizationConfig:
    """Конфигурация оптимизации для multiple shooting."""
    def __init__(self, n_obs):
        self.gamma = np.ones(n_obs)      # веса измерений
        self.lambda_ = 0.01                # регуляризация Левенберга-Марквардта
        self.lambda_reg = 0.0001               # дополнительная регуляризация (отключена)
        self.n_iter = 30                   # количество итераций
        self.c0_cost = 1.0                  # вес начальной точки в интервале
        self.validation = False             # режим валидации
        self.mu = 1.0                     # начальный параметр для метода с множителями
        self.n_shoot = 50
        self.mu_min = 1e-6
        self.mu_dec = 0.7

def setup_problem(system, config, state_measured_batches, 
                  t_eval_batches, t_eval_debug, state_full_debug, theta_true):
    problem = MultipleShooting(system, N_shoot=config.n_shoot, gamma=config.gamma,
                               c0_cost=config.c0_cost, use_jax=True)
    for state_meas, t_meas in zip(state_measured_batches, t_eval_batches):
        problem.add_batch(state_meas, t_meas)
    problem.full_trajectory = (t_eval_debug, state_full_debug)
    problem.theta_true = theta_true
    return problem

# ====================================================================
# Основной блок (исправлен)
# ====================================================================
if __name__ == "__main__":

    config = OptimizationConfig(system.n_obs)
    # При необходимости переопределите параметры:
    problem = setup_problem(system, config,
                            measured_batches, t_batches,
                            t_batches_debug, state_batches_debug, theta_true)
    theta0 = theta_init   # theta определена ранее

    theta_full = problem.make_full_theta(theta0, n_iter = 10)
    theta_hist, r_meas_hist, r_cont_hist, theta_full, ci_low_hist, ci_high_hist = run_optimization(
        problem, config, theta_full, system
    )


  J nnz: 441, J_G nnz: 1008
Iter   0 | R_meas: 8.864e-16 | R_cont: 2.672e+01 | mu: 1.00e+00
  Iter time: 0.008s
Iter   1 | R_meas: 1.121e-01 | R_cont: 1.732e+00 | mu: 7.00e-01
  Iter time: 0.008s
Iter   2 | R_meas: 2.364e-04 | R_cont: 3.160e-03 | mu: 4.90e-01
  Iter time: 0.007s
Iter   3 | R_meas: 1.587e-08 | R_cont: 5.427e-08 | mu: 3.43e-01
  Iter time: 0.007s
Iter   4 | R_meas: 2.239e-09 | R_cont: 2.152e-09 | mu: 2.40e-01
  Iter time: 0.007s
Iter   5 | R_meas: 2.797e-09 | R_cont: 1.901e-09 | mu: 1.68e-01
  Шаг отклонён (cost 9.953e-07 > 6.850e-07), mu сохранён 1.68e-01
  Iter time: 0.007s
Iter   6 | R_meas: 2.797e-09 | R_cont: 1.901e-09 | mu: 2.40e-01
  Шаг отклонён (cost 7.999e-07 > 6.850e-07), mu сохранён 2.40e-01
  Iter time: 0.008s
Iter   7 | R_meas: 2.797e-09 | R_cont: 1.901e-09 | mu: 3.43e-01
  Iter time: 0.007s
Iter   8 | R_meas: 2.243e-09 | R_cont: 1.738e-09 | mu: 2.40e-01
  Iter time: 0.007s
Iter   9 | R_meas: 2.800e-09 | R_cont: 1.507e-09 | mu: 1.68e-01
  Шаг отклонён (cost

In [11]:

plot_solution(
    problem = problem, 
    theta_hist = theta_hist,
    plot_xy=1,
    plot_theta=True,
    plot_trajectory=0,
    plot_true_solution=False,
    plot_residuals=True,
    plot_measurements = 1,
    r_meas_hist=r_meas_hist,
    r_cont_hist=r_cont_hist,
    index=-1,
    theta_true=None,
    # ci_low_hist=ci_low_hist,    # <-- добавить
    # ci_high_hist=ci_high_hist,  # <-- добавить
    #state_names=['a_y', 'w_z'],
    #param_names=['C<sub>f</sub>', 'C<sub>r</sub>', 'a<sub>rel</sub>', 'I<sub>norm</sub>']
   # param_names=[f'θ_{i}' for i in range( system.np)]
)

In [11]:
fig = plt.figure(figsize=(30, 25))
plot_solution(
    fig = None, problem, theta_hist,
    plot_xy=1,
    plot_theta=True,
    plot_true_solution=True,
    plot_residuals=True,
    plot_measurements = 1,
    r_meas_hist=r_meas_hist,
    r_cont_hist=r_cont_hist,
    index=0,
    theta_true=theta_true,
    ci_low_hist=ci_low_hist,    # <-- добавить
    ci_high_hist=ci_high_hist,  # <-- добавить
    param_names=[f'θ_{i}' for i in range( system.np)]
)

SyntaxError: positional argument follows keyword argument (3507514375.py, line 16)

In [41]:
theta_true, theta_hist[-1][:len(theta_true)]

(array([ 0.05      , -0.08726646]), array([ 0.05145798, -0.10184656]))

In [29]:
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.animation as animation

fig = plt.figure(figsize=(30, 25))

def animate_gauss(frame):
    fig.clear()
    plt.clf()
    plot_solution(
    fig, 
    problem, 
    theta_hist, 
    plot_xy=0,               # покажет x(t) и y(t)
    plot_theta=1,            # покажет сходимость параметров
    plot_true_solution=True,    # если есть истинная траектория
    plot_residuals=0,        # добавить график невязок
    r_meas_hist=r_meas_hist,    # ваша история невязок измерений
    r_cont_hist=r_cont_hist,     # ваша история невязок непрерывности
    index=frame,                   # последняя итерация
    theta_true=theta_true       # истинные параметры (опционально)
)
anim = animation.FuncAnimation(
    fig, animate_gauss, frames=10, interval=500, repeat=True
)

plt.show()

<Figure size 3000x2500 with 0 Axes>

In [22]:
anim.save("gauss_newton/demo.gif", writer="pillow")

batch 0
batch 0
batch 0
batch 0
batch 0
batch 0
batch 0
batch 0
batch 0
batch 0
batch 0


<Figure size 640x480 with 0 Axes>